// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: metadata.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Custom metadata item as a key-value pair
type MetadataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetadataItem_BoolValue
	//	*MetadataItem_IntValue
	//	*MetadataItem_FloatValue
	//	*MetadataItem_StringValue
	Value         isMetadataItem_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataItem) Reset() {
	*x = MetadataItem{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataItem) ProtoMessage() {}

func (x *MetadataItem) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataItem.ProtoReflect.Descriptor instead.
func (*MetadataItem) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataItem) GetValue() isMetadataItem_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetadataItem) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MetadataItem_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MetadataItem) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*MetadataItem_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetadataItem) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*MetadataItem_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *MetadataItem) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataItem_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isMetadataItem_Value interface {
	isMetadataItem_Value()
}

type MetadataItem_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MetadataItem_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetadataItem_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type MetadataItem_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*MetadataItem_BoolValue) isMetadataItem_Value() {}

func (*MetadataItem_IntValue) isMetadataItem_Value() {}

func (*MetadataItem_FloatValue) isMetadataItem_Value() {}

func (*MetadataItem_StringValue) isMetadataItem_Value() {}

// Image metadata definition
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	Timestamp     int32                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BitsPixel     int32                  `protobuf:"varint,6,opt,name=bits_pixel,json=bitsPixel,proto3" json:"bits_pixel,omitempty"`
	Obid          int32                  `protobuf:"varint,7,opt,name=obid,proto3" json:"obid,omitempty"`
	Camera        string                 `protobuf:"bytes,8,opt,name=camera,proto3" json:"camera,omitempty"`
	Items         []*MetadataItem        `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Metadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Metadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Metadata) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Metadata) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metadata) GetBitsPixel() int32 {
	if x != nil {
		return x.BitsPixel
	}
	return 0
}

func (x *Metadata) GetObid() int32 {
	if x != nil {
		return x.Obid
	}
	return 0
}

func (x *Metadata) GetCamera() string {
	if x != nil {
		return x.Camera
	}
	return ""
}

func (x *Metadata) GetItems() []*MetadataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\"\xb1\x01\n" +
	"\fMetadataItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x05H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"\xf6\x01\n" +
	"\bMetadata\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x05R\ttimestamp\x12\x1d\n" +
	"\n" +
	"bits_pixel\x18\x06 \x01(\x05R\tbitsPixel\x12\x12\n" +
	"\x04obid\x18\a \x01(\x05R\x04obid\x12\x16\n" +
	"\x06camera\x18\b \x01(\tR\x06camera\x12#\n" +
	"\x05items\x18\t \x03(\v2\r.MetadataItemR\x05itemsB\tZ\a./;mainb\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_proto_goTypes = []any{
	(*MetadataItem)(nil), // 0: MetadataItem
	(*Metadata)(nil),     // 1: Metadata
}
var file_metadata_proto_depIdxs = []int32{
	0, // 0: Metadata.items:type_name -> MetadataItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	file_metadata_proto_msgTypes[0].OneofWrappers = []any{
		(*MetadataItem_BoolValue)(nil),
		(*MetadataItem_IntValue)(nil),
		(*MetadataItem_FloatValue)(nil),
		(*MetadataItem_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
